In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Advertising.csv")

In [ ]:
df

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df = df.drop('Unnamed: 0',axis=1)

In [ ]:
df.head(3)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3

In [ ]:
from sklearn.model_selection import train_test_split as tts

Extracting features from dataframe to get array or metrics form of data.

In [ ]:
x = df[['TV','Radio','Newspaper']].values
y = df['Sales'].values

In [ ]:
y

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16.1, 11.6, 16.6, 19. ,
       15.6,  3.2, 15.3, 10.1,  7.3, 12.9, 14.4, 13.3, 14.9, 18. , 11.9,
       11.9,  8. , 12.2, 17.1, 15. ,  8.4, 14.5,  7.6, 11.7, 11.5, 27. ,
       20.2, 11.7, 11.8, 12.6, 10.5, 12.2,  8.7, 26.2, 17.6, 22.6, 10.3,
       17.3, 15.9,  6.7, 10.8,  9.9,  5.9, 19.6, 17.3,  7.6,  9.7, 12.8,
       25.5, 13.4])

In [ ]:
y.shape

(200,)

Linear regression math assumes:

𝑦
∈
𝑅
𝑛
×
1
y∈R
n×1

That means:

 y
=
[
22.1


10.4


9.3
]


y=
	​
[
22.1
10.4
9.3
]

But NumPy’s (n,) array is neither:

(n,1) → column vector ❌

(1,n) → row vector ❌

So when you do matrix math like:

means:

“I want 1 column, and NumPy should figure out how many rows are needed.”

The -1 is NumPy’s way of saying:

“Compute this automatically.”

In [ ]:
y = y.reshape(-1,1)
y.shape

(200, 1)

here we get our shape as n*1

In [ ]:
x.shape

(200, 3)

Adding bias intercept column

In [ ]:
x.shape[0]

200

In [ ]:
m = x.shape[0]
x_b = np.hstack([np.ones((m,1)),x])

In [ ]:
x_b

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ],
       [  1. ,  57.5,  32.8,  23.5],
       [  1. , 120.2,  19.6,  11.6],
       [  1. ,   8.6,   2.1,   1. ],
       [  1. , 199.8,   2.6,  21.2],
       [  1. ,  66.1,   5.8,  24.2],
       [  1. , 214.7,  24. ,   4. ],
       [  1. ,  23.8,  35.1,  65.9],
       [  1. ,  97.5,   7.6,   7.2],
       [  1. , 204.1,  32.9,  46. ],
       [  1. , 195.4,  47.7,  52.9],
       [  1. ,  67.8,  36.6, 114. ],
       [  1. , 281.4,  39.6,  55.8],
       [  1. ,  69.2,  20.5,  18.3],
       [  1. , 147.3,  23.9,  19.1],
       [  1. , 218.4,  27.7,  53.4],
       [  1. , 237.4,   5.1,  23.5],
       [  1. ,  13.2,  15.9,  49.6],
       [  1. , 228.3,  16.9,  26.2],
       [  1. ,  62.3,  12.6,  18.3],
       [  1. , 262.9,   3.5,  19.5],
       [  1. , 142.9,  29.3,  12.6],
       [  1. , 240.1,  16.7,  22.9],
       [  1. , 248.8,  27.1,  22.9],
       [  1. ,  70.6,  16. ,  40.8],
       [  1. , 292.9,  28.3,  43.2],
       [  1. , 112.9,  17.4,  38.6],
       [  1. ,  97.2,   1.5,  30. ],
       [  1. , 265.6,  20. ,   0.3],
       [  1. ,  95.7,   1.4,   7.4],
       [  1. , 290.7,   4.1,   8.5],
       [  1. , 266.9,  43.8,   5. ],
       [  1. ,  74.7,  49.4,  45.7],
       [  1. ,  43.1,  26.7,  35.1],
       [  1. , 228. ,  37.7,  32. ],
       [  1. , 202.5,  22.3,  31.6],
       [  1. , 177. ,  33.4,  38.7],
       [  1. , 293.6,  27.7,   1.8],
       [  1. , 206.9,   8.4,  26.4],
       [  1. ,  25.1,  25.7,  43.3],
       [  1. , 175.1,  22.5,  31.5],
       [  1. ,  89.7,   9.9,  35.7],
       [  1. , 239.9,  41.5,  18.5],
       [  1. , 227.2,  15.8,  49.9],
       [  1. ,  66.9,  11.7,  36.8],
       [  1. , 199.8,   3.1,  34.6],
       [  1. , 100.4,   9.6,   3.6],
       [  1. , 216.4,  41.7,  39.6],
       [  1. , 182.6,  46.2,  58.7],
       [  1. , 262.7,  28.8,  15.9],
       [  1. , 198.9,  49.4,  60. ],
       [  1. ,   7.3,  28.1,  41.4],
       [  1. , 136.2,  19.2,  16.6],
       [  1. , 210.8,  49.6,  37.7],
       [  1. , 210.7,  29.5,   9.3],
       [  1. ,  53.5,   2. ,  21.4],
       [  1. , 261.3,  42.7,  54.7],
       [  1. , 239.3,  15.5,  27.3],
       [  1. , 102.7,  29.6,   8.4],
       [  1. , 131.1,  42.8,  28.9],
       [  1. ,  69. ,   9.3,   0.9],
       [  1. ,  31.5,  24.6,   2.2],
       [  1. , 139.3,  14.5,  10.2],
       [  1. , 237.4,  27.5,  11. ],
       [  1. , 216.8,  43.9,  27.2],
       [  1. , 199.1,  30.6,  38.7],
       [  1. , 109.8,  14.3,  31.7],
       [  1. ,  26.8,  33. ,  19.3],
       [  1. , 129.4,   5.7,  31.3],
       [  1. , 213.4,  24.6,  13.1],
       [  1. ,  16.9,  43.7,  89.4],
       [  1. ,  27.5,   1.6,  20.7],
       [  1. , 120.5,  28.5,  14.2],
       [  1. ,   5.4,  29.9,   9.4],
       [  1. , 116. ,   7.7,  23.1],
       [  1. ,  76.4,  26.7,  22.3],
       [  1. , 239.8,   4.1,  36.9],
       [  1. ,  75.3,  20.3,  32.5],
       [  1. ,  68.4,  44.5,  35.6],
       [  1. , 213.5,  43. ,  33.8],
       [  1. , 193.2,  18.4,  65.7],
       [  1. ,  76.3,  27.5,  16. ],
       [  1. , 110.7,  40.6,  63.2],
       [  1. ,  88.3,  25.5,  73.4],
       [  1. , 109.8,  47.8,  51.4],
       [  1. , 134.3,   4.9,   9.3],
       [  1. ,  28.6,   1.5,  33. ],
       [  1. , 217.7,  33.5,  59. ],
       [  1. , 250.9,  36.5,  72.3],
       [  1. , 107.4,  14. ,  10.9],
       [  1. , 163.3,  31.6,  52.9],
       [  1. , 197.6,   3.5,   5.9],
       [  1. , 184.9,  21. ,  22. ],
       [  1. , 289.7,  42.3,  51.2],
       [  1. , 135.2,  41.7,  45.9],
       [  1. , 222.4,   4.3,  49.8],
       [  1. , 296.4,  36.3, 100.9],
       [  1. , 280.2,  10.1,  21.4],
       [  1. , 187.9,  17.2,  17.9],
       [  1. , 238.2,  34.3,   5.3],
       [  1. , 137.9,  46.4,  59. ],
       [  1. ,  25. ,  11. ,  29.7],
       [  1. ,  90.4,   0.3,  23.2],
       [  1. ,  13.1,   0.4,  25.6],
       [  1. , 255.4,  26.9,   5.5],
       [  1. , 225.8,   8.2,  56.5],
       [  1. , 241.7,  38. ,  23.2],
       [  1. , 175.7,  15.4,   2.4],
       [  1. , 209.6,  20.6,  10.7],
       [  1. ,  78.2,  46.8,  34.5],
       [  1. ,  75.1,  35. ,  52.7],
       [  1. , 139.2,  14.3,  25.6],
       [  1. ,  76.4,   0.8,  14.8],
       [  1. , 125.7,  36.9,  79.2],
       [  1. ,  19.4,  16. ,  22.3],
       [  1. , 141.3,  26.8,  46.2],
       [  1. ,  18.8,  21.7,  50.4],
       [  1. , 224. ,   2.4,  15.6],
       [  1. , 123.1,  34.6,  12.4],
       [  1. , 229.5,  32.3,  74.2],
       [  1. ,  87.2,  11.8,  25.9],
       [  1. ,   7.8,  38.9,  50.6],
       [  1. ,  80.2,   0. ,   9.2],
       [  1. , 220.3,  49. ,   3.2],
       [  1. ,  59.6,  12. ,  43.1],
       [  1. ,   0.7,  39.6,   8.7],
       [  1. , 265.2,   2.9,  43. ],
       [  1. ,   8.4,  27.2,   2.1],
       [  1. , 219.8,  33.5,  45.1],
       [  1. ,  36.9,  38.6,  65.6],
       [  1. ,  48.3,  47. ,   8.5],
       [  1. ,  25.6,  39. ,   9.3],
       [  1. , 273.7,  28.9,  59.7],
       [  1. ,  43. ,  25.9,  20.5],
       [  1. , 184.9,  43.9,   1.7],
       [  1. ,  73.4,  17. ,  12.9],
       [  1. , 193.7,  35.4,  75.6],
       [  1. , 220.5,  33.2,  37.9],
       [  1. , 104.6,   5.7,  34.4],
       [  1. ,  96.2,  14.8,  38.9],
       [  1. , 140.3,   1.9,   9. ],
       [  1. , 240.1,   7.3,   8.7],
       [  1. , 243.2,  49. ,  44.3],
       [  1. ,  38. ,  40.3,  11.9],
       [  1. ,  44.7,  25.8,  20.6],
       [  1. , 280.7,  13.9,  37. ],
       [  1. , 121. ,   8.4,  48.7],
       [  1. , 197.6,  23.3,  14.2],
       [  1. , 171.3,  39.7,  37.7],
       [  1. , 187.8,  21.1,   9.5],
       [  1. ,   4.1,  11.6,   5.7],
       [  1. ,  93.9,  43.5,  50.5],
       [  1. , 149.8,   1.3,  24.3],
       [  1. ,  11.7,  36.9,  45.2],
       [  1. , 131.7,  18.4,  34.6],
       [  1. , 172.5,  18.1,  30.7],
       [  1. ,  85.7,  35.8,  49.3],
       [  1. , 188.4,  18.1,  25.6],
       [  1. , 163.5,  36.8,   7.4],
       [  1. , 117.2,  14.7,   5.4],
       [  1. , 234.5,   3.4,  84.8],
       [  1. ,  17.9,  37.6,  21.6],
       [  1. , 206.8,   5.2,  19.4],
       [  1. , 215.4,  23.6,  57.6],
       [  1. , 284.3,  10.6,   6.4],
       [  1. ,  50. ,  11.6,  18.4],
       [  1. , 164.5,  20.9,  47.4],
       [  1. ,  19.6,  20.1,  17. ],
       [  1. , 168.4,   7.1,  12.8],
       [  1. , 222.4,   3.4,  13.1],
       [  1. , 276.9,  48.9,  41.8],
       [  1. , 248.4,  30.2,  20.3],
       [  1. , 170.2,   7.8,  35.2],
       [  1. , 276.7,   2.3,  23.7],
       [  1. , 165.6,  10. ,  17.6],
       [  1. , 156.6,   2.6,   8.3],
       [  1. , 218.5,   5.4,  27.4],
       [  1. ,  56.2,   5.7,  29.7],
       [  1. , 287.6,  43. ,  71.8],
       [  1. , 253.8,  21.3,  30. ],
       [  1. , 205. ,  45.1,  19.6],
       [  1. , 139.5,   2.1,  26.6],
       [  1. , 191.1,  28.7,  18.2],
       [  1. , 286. ,  13.9,   3.7],
       [  1. ,  18.7,  12.1,  23.4],
       [  1. ,  39.5,  41.1,   5.8],
       [  1. ,  75.5,  10.8,   6. ],
       [  1. ,  17.2,   4.1,  31.6],
       [  1. , 166.8,  42. ,   3.6],
       [  1. , 149.7,  35.6,   6. ],
       [  1. ,  38.2,   3.7,  13.8],
       [  1. ,  94.2,   4.9,   8.1],
       [  1. , 177. ,   9.3,   6.4],
       [  1. , 283.6,  42. ,  66.2],
       [  1. , 232.1,   8.6,   8.7]])

here we get our shape as n*(m+1)

Transposing x

In [ ]:
x_t = x_b.T

In [ ]:
x_t

array([[  1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ],
       [230.1,  44.5,  17.2, 151.5, 180.8,   8.7,  57.5, 120.2,   8.6,
        199.8,  66.1, 214.7,  23.8,  97.5, 204.1, 195.4,  67.8, 281.4,
         69.2, 147.3, 218.4, 237.4,  13.2, 228.3,  62.3, 262.9, 142.9,
        240.1, 248.8,  70.6, 292.9, 112.9,  97.2, 265.6,  95.7, 290.7,
        266.9,  74.7,  43.1, 228. , 202.5, 177. , 293.6, 206.9,  25.1,
        175.1,  89.7, 239.9, 227.2,  66.9, 199.8, 100.4, 216.4, 182.6,
        262.7, 198.9,   7.3, 136.2, 210.8, 210.7,  53.5, 261.3, 239.3,
        102.7, 131.1,  69. ,  31.5, 139.3, 237.4, 216.8, 199.1, 109.8,
         26.8, 129.4, 213.4,  16.9,  27.5, 120.5,   5.4, 116. ,  76.4,
        239.8,  75.3,  68.4, 213.5, 193.2,  76.3, 110.7,  88.3, 109.8,
        134.3,  28.6, 217.7, 250.9, 107.4, 163.3, 197.6, 184.9, 289.7,
        135.2, 222.4, 296.4, 280.2, 187.9, 238.2, 137.9,  25. ,  90.4,
         13.1, 255.4, 225.8, 241.7, 175.7, 209.6,  78.2,  75.1, 139.2,
         76.4, 125.7,  19.4, 141.3,  18.8, 224. , 123.1, 229.5,  87.2,
          7.8,  80.2, 220.3,  59.6,   0.7, 265.2,   8.4, 219.8,  36.9,
         48.3,  25.6, 273.7,  43. , 184.9,  73.4, 193.7, 220.5, 104.6,
         96.2, 140.3, 240.1, 243.2,  38. ,  44.7, 280.7, 121. , 197.6,
        171.3, 187.8,   4.1,  93.9, 149.8,  11.7, 131.7, 172.5,  85.7,
        188.4, 163.5, 117.2, 234.5,  17.9, 206.8, 215.4, 284.3,  50. ,
        164.5,  19.6, 168.4, 222.4, 276.9, 248.4, 170.2, 276.7, 165.6,
        156.6, 218.5,  56.2, 287.6, 253.8, 205. , 139.5, 191.1, 286. ,
         18.7,  39.5,  75.5,  17.2, 166.8, 149.7,  38.2,  94.2, 177. ,
        283.6, 232.1],
       [ 37.8,  39.3,  45.9,  41.3,  10.8,  48.9,  32.8,  19.6,   2.1,
          2.6,   5.8,  24. ,  35.1,   7.6,  32.9,  47.7,  36.6,  39.6,
         20.5,  23.9,  27.7,   5.1,  15.9,  16.9,  12.6,   3.5,  29.3,
         16.7,  27.1,  16. ,  28.3,  17.4,   1.5,  20. ,   1.4,   4.1,
         43.8,  49.4,  26.7,  37.7,  22.3,  33.4,  27.7,   8.4,  25.7,
         22.5,   9.9,  41.5,  15.8,  11.7,   3.1,   9.6,  41.7,  46.2,
         28.8,  49.4,  28.1,  19.2,  49.6,  29.5,   2. ,  42.7,  15.5,
         29.6,  42.8,   9.3,  24.6,  14.5,  27.5,  43.9,  30.6,  14.3,
         33. ,   5.7,  24.6,  43.7,   1.6,  28.5,  29.9,   7.7,  26.7,
          4.1,  20.3,  44.5,  43. ,  18.4,  27.5,  40.6,  25.5,  47.8,
          4.9,   1.5,  33.5,  36.5,  14. ,  31.6,   3.5,  21. ,  42.3,
         41.7,   4.3,  36.3,  10.1,  17.2,  34.3,  46.4,  11. ,   0.3,
          0.4,  26.9,   8.2,  38. ,  15.4,  20.6,  46.8,  35. ,  14.3,
          0.8,  36.9,  16. ,  26.8,  21.7,   2.4,  34.6,  32.3,  11.8,
         38.9,   0. ,  49. ,  12. ,  39.6,   2.9,  27.2,  33.5,  38.6,
         47. ,  39. ,  28.9,  25.9,  43.9,  17. ,  35.4,  33.2,   5.7,
         14.8,   1.9,   7.3,  49. ,  40.3,  25.8,  13.9,   8.4,  23.3,
         39.7,  21.1,  11.6,  43.5,   1.3,  36.9,  18.4,  18.1,  35.8,
         18.1,  36.8,  14.7,   3.4,  37.6,   5.2,  23.6,  10.6,  11.6,
         20.9,  20.1,   7.1,   3.4,  48.9,  30.2,   7.8,   2.3,  10. ,
          2.6,   5.4,   5.7,  43. ,  21.3,  45.1,   2.1,  28.7,  13.9,
         12.1,  41.1,  10.8,   4.1,  42. ,  35.6,   3.7,   4.9,   9.3,
         42. ,   8.6],
       [ 69.2,  45.1,  69.3,  58.5,  58.4,  75. ,  23.5,  11.6,   1. ,
         21.2,  24.2,   4. ,  65.9,   7.2,  46. ,  52.9, 114. ,  55.8,
         18.3,  19.1,  53.4,  23.5,  49.6,  26.2,  18.3,  19.5,  12.6,
         22.9,  22.9,  40.8,  43.2,  38.6,  30. ,   0.3,   7.4,   8.5,
          5. ,  45.7,  35.1,  32. ,  31.6,  38.7,   1.8,  26.4,  43.3,
         31.5,  35.7,  18.5,  49.9,  36.8,  34.6,   3.6,  39.6,  58.7,
         15.9,  60. ,  41.4,  16.6,  37.7,   9.3,  21.4,  54.7,  27.3,
          8.4,  28.9,   0.9,   2.2,  10.2,  11. ,  27.2,  38.7,  31.7,
         19.3,  31.3,  13.1,  89.4,  20.7,  14.2,   9.4,  23.1,  22.3,
         36.9,  32.5,  35.6,  33.8,  65.7,  16. ,  63.2,  73.4,  51.4,
          9.3,  33. ,  59. ,  72.3,  10.9,  52.9,   5.9,  22. ,  51.2,
         45.9,  49.8, 100.9,  21.4,  17.9,   5.3,  59. ,  29.7,  23.2,
         25.6,   5.5,  56.5,  23.2,   2.4,  10.7,  34.5,  52.7,  25.6,
         14.8,  79.2,  22.3,  46.2,  50.4,  15.6,  12.4,  74.2,  25.9,
         50.6,   9.2,   3.2,  43.1,   8.7,  43. ,   2.1,  45.1,  65.6,
          8.5,   9.3,  59.7,  20.5,   1.7,  12.9,  75.6,  37.9,  34.4,
         38.9,   9. ,   8.7,  44.3,  11.9,  20.6,  37. ,  48.7,  14.2,
         37.7,   9.5,   5.7,  50.5,  24.3,  45.2,  34.6,  30.7,  49.3,
         25.6,   7.4,   5.4,  84.8,  21.6,  19.4,  57.6,   6.4,  18.4,
         47.4,  17. ,  12.8,  13.1,  41.8,  20.3,  35.2,  23.7,  17.6,
          8.3,  27.4,  29.7,  71.8,  30. ,  19.6,  26.6,  18.2,   3.7,
         23.4,   5.8,   6. ,  31.6,   3.6,   6. ,  13.8,   8.1,   6.4,
         66.2,   8.7]])

What does @ mean?

Matrix multiplication (not element-wise)

Mathematically:

𝑋
𝑇
𝑋


This matrix:

captures correlations between features

must be invertible for the normal equation

In [ ]:
xtx = x_t @ x_b

In [ ]:
xtx

array([[2.00000000e+02, 2.94085000e+04, 4.65280000e+03, 6.11080000e+03],
       [2.94085000e+04, 5.79111839e+06, 6.98061980e+05, 9.19625280e+05],
       [4.65280000e+03, 6.98061980e+05, 1.52107860e+05, 1.64946550e+05],
       [6.11080000e+03, 9.19625280e+05, 1.64946550e+05, 2.81096740e+05]])

Inverse of xtx

In [ ]:
xtx_inv = np.linalg.inv(xtx)

In [ ]:
xtx_inv

array([[ 3.42444998e-02, -9.35348333e-05, -3.92647297e-04,
        -2.08036831e-04],
       [-9.35348333e-05,  6.84890750e-07, -1.57355890e-07,
        -1.14959987e-07],
       [-3.92647297e-04, -1.57355890e-07,  2.61016474e-05,
        -6.26574016e-06],
       [-2.08036831e-04, -1.14959987e-07, -6.26574016e-06,
         1.21328472e-05]])

xt*y

In [ ]:
xt_y = x_t @ y

Final beta computation

In [ ]:
beta = xtx_inv @ xt_y

In [ ]:
beta

array([[ 2.93888937e+00],
       [ 4.57646455e-02],
       [ 1.88530017e-01],
       [-1.03749304e-03]])

In [ ]:
print("Intercept:", beta[0])
print("TV coefficient:", beta[1])
print("Radio coefficient:", beta[2])
print("Newspaper coefficient:", beta[3])

Intercept: [2.93888937]
TV coefficient: [0.04576465]
Radio coefficient: [0.18853002]
Newspaper coefficient: [-0.00103749]

In [ ]:
y_pred = x_b @ beta

In [ ]:
y_pred

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872],
       [ 7.0322992 ],
       [17.28512918],
       [10.57712073],
       [ 8.82630048],
       [18.43436638],
       [20.81929952],
       [12.82365674],
       [23.22495716],
       [ 9.95168206],
       [14.16607293],
       [18.10076728],
       [14.7405382 ],
       [ 6.4891503 ],
       [16.5459329 ],
       [ 8.14651887],
       [15.6100386 ],
       [14.98951429],
       [17.05167344],
       [19.41053803],
       [ 9.14402389],
       [21.6339338 ],
       [11.3460929 ],
       [ 7.63888314],
       [18.86426829],
       [ 7.57483051],
       [17.00682618],
       [23.40590052],
       [15.62347779],
       [ 9.90868103],
       [20.44761039],
       [16.37766467],
       [17.2959832 ],
       [21.59580326],
       [13.96385684],
       [ 8.88787996],
       [15.16152314],
       [ 8.87338673],
       [21.7226299 ],
       [16.26362018],
       [ 8.1681656 ],
       [12.63121132],
       [ 9.33981296],
       [20.66297563],
       [19.94469957],
       [20.37443008],
       [21.2926106 ],
       [ 8.52771254],
       [12.77458802],
       [21.89805198],
       [18.13348698],
       [ 5.74215558],
       [22.89067208],
       [16.78426073],
       [13.21069202],
       [16.97773556],
       [ 7.84904532],
       [ 9.01603163],
       [12.0370073 ],
       [18.97657924],
       [21.10891244],
       [17.77949782],
       [10.62693815],
       [10.36684881],
       [ 9.90298206],
       [17.32931197],
       [11.85832174],
       [ 4.47758904],
       [13.81190223],
       [ 8.81331353],
       [ 9.67530328],
       [11.44592364],
       [14.64794093],
       [10.17840799],
       [14.42184212],
       [20.78136464],
       [15.18140789],
       [11.59870739],
       [15.59378475],
       [11.71127101],
       [16.92225511],
       [ 9.99922965],
       [ 4.49631598],
       [19.15639616],
       [21.22757378],
       [10.48212385],
       [16.31492112],
       [12.63571716],
       [15.33707782],
       [24.11860723],
       [16.94035021],
       [13.87595844],
       [23.24248685],
       [17.64409385],
       [14.76221142],
       [20.30110878],
       [17.93641467],
       [ 6.12602215],
       [ 7.10850249],
       [ 3.58725841],
       [19.69293106],
       [14.7598741 ],
       [21.14027498],
       [13.88060985],
       [16.40377623],
       [15.30509593],
       [12.91968895],
       [11.97874744],
       [ 6.5707774 ],
       [15.56609348],
       [ 6.82006767],
       [14.41010605],
       [ 7.83807642],
       [13.6264571 ],
       [15.0827909 ],
       [19.45441306],
       [ 9.12734958],
       [10.57717411],
       [ 6.599669  ],
       [22.25549161],
       [ 7.88410649],
       [10.4276871 ],
       [15.57779819],
       [ 8.44915012],
       [19.26692307],
       [11.8368039 ],
       [14.00141385],
       [11.45348627],
       [20.85125198],
       [ 9.76842795],
       [19.67547632],
       [ 9.48964097],
       [18.39902932],
       [19.24986927],
       [ 8.76480262],
       [10.09133403],
       [ 9.70853872],
       [15.29422368],
       [23.26086103],
       [12.26335941],
       [ 9.8272711 ],
       [18.36720534],
       [10.0095377 ],
       [16.3600003 ],
       [18.22390132],
       [15.50161696],
       [ 5.3075589 ],
       [15.38485192],
       [10.0143112 ],
       [10.38419866],
       [12.39914823],
       [14.21383298],
       [13.55914568],
       [14.94678206],
       [17.35163608],
       [11.0682946 ],
       [14.22372138],
       [10.82439531],
       [13.36324677],
       [17.1861428 ],
       [17.9415563 ],
       [ 7.39497997],
       [14.35827373],
       [ 7.60769238],
       [11.97093887],
       [13.74435742],
       [24.78687031],
       [19.9793727 ],
       [12.1620464 ],
       [16.01099722],
       [12.38455495],
       [10.5871997 ],
       [13.92809918],
       [ 6.55467   ],
       [24.13310013],
       [18.53852096],
       [20.80301059],
       [ 9.69137313],
       [17.07644223],
       [18.64430648],
       [ 6.05162411],
       [12.4891591 ],
       [ 8.42401933],
       [ 4.46622956],
       [18.48695797],
       [16.49530044],
       [ 5.37034248],
       [ 8.16531236],
       [12.78592082],
       [23.76732149],
       [15.17319554]])

<h1> modular coding

In [ ]:
# x_train, x_test, y_train, y_test = tts(x,y,test_size=0.2,random_state=42)

In [ ]:
# print(x_train.shape)
# print(y_train.shape)
# print(x_test.shape)
# print(y_test.shape)

In [ ]:
# x_train

<h1> using normal equation on train test split

In [ ]:
def multi_lr(x: pd.DataFrame, y: pd.Series):

    x_train, x_test, y_train, y_test = tts(
        x, y, test_size=0.2, random_state=42
    )

    # Ensure y_train is column vector
    y_train = np.asarray(y_train).reshape(-1, 1)

    # Convert X to NumPy
    x_train = np.asarray(x_train)
    x_test = np.asarray(x_test)

    # Add bias column
    m = x_train.shape[0]
    x_b = np.hstack([np.ones((m, 1)), x_train])

    # Normal Equation
    x_t = x_b.T
    beta = np.linalg.inv(x_t @ x_b) @ (x_t @ y_train)

    print("Intercept:", beta[0])
    print("TV coefficient:", beta[1])
    print("Radio coefficient:", beta[2])
    print("Newspaper coefficient:", beta[3])

    # Prediction
    m_test = x_test.shape[0]
    x_test_b = np.hstack([np.ones((m_test, 1)), x_test])
    y_pred = x_test_b @ beta

    return beta, y_pred, x_test, y_test

In [ ]:
lr = multi_lr(x,y)

Intercept: [2.97906734]
TV coefficient: [0.04472952]
Radio coefficient: [0.18919505]
Newspaper coefficient: [0.00276111]

In [ ]:
from sklearn.metrics import r2_score

# Unpack x_test, y_pred, and y_test from the lr tuple
_, y_pred, x_test, y_test = lr

r2_score(y_test, y_pred)

0.8994380241009124

<h1> using Normal equation full dataset training

In [ ]:
def multi_lr(x: pd.Series, y: pd.Series):

  # reshape y to n*1
  y = y.reshape(-1,1)
  y.shape

  # adding bias column into x
  m = x.shape[0]
  x_b = np.hstack([np.ones((m,1)),x])

  # transposing of x_b
  x_t = x_b.T

  # x_t * x_b
  xtx = x_t @ x_b

  # inverse of xtx
  xtx_inv = np.linalg.inv(xtx)

  # x_t * y
  xt_y = x_t @ y

  # final beta computation
  beta = xtx_inv @ xt_y

  print("Intercept:", beta[0])
  print("TV coefficient:", beta[1])
  print("Radio coefficient:", beta[2])
  print("Newspaper coefficient:", beta[3])

  y_pred = x_b @ beta

  return beta, y_pred

In [ ]:
ml = multi_lr(x,y)

Intercept: [2.93888937]
TV coefficient: [0.04576465]
Radio coefficient: [0.18853002]
Newspaper coefficient: [-0.00103749]

In [ ]:
predictions = ml[1]

In [ ]:
predictions

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872],
       [ 7.0322992 ],
       [17.28512918],
       [10.57712073],
       [ 8.82630048],
       [18.43436638],
       [20.81929952],
       [12.82365674],
       [23.22495716],
       [ 9.95168206],
       [14.16607293],
       [18.10076728],
       [14.7405382 ],
       [ 6.4891503 ],
       [16.5459329 ],
       [ 8.14651887],
       [15.6100386 ],
       [14.98951429],
       [17.05167344],
       [19.41053803],
       [ 9.14402389],
       [21.6339338 ],
       [11.3460929 ],
       [ 7.63888314],
       [18.86426829],
       [ 7.57483051],
       [17.00682618],
       [23.40590052],
       [15.62347779],
       [ 9.90868103],
       [20.44761039],
       [16.37766467],
       [17.2959832 ],
       [21.59580326],
       [13.96385684],
       [ 8.88787996],
       [15.16152314],
       [ 8.87338673],
       [21.7226299 ],
       [16.26362018],
       [ 8.1681656 ],
       [12.63121132],
       [ 9.33981296],
       [20.66297563],
       [19.94469957],
       [20.37443008],
       [21.2926106 ],
       [ 8.52771254],
       [12.77458802],
       [21.89805198],
       [18.13348698],
       [ 5.74215558],
       [22.89067208],
       [16.78426073],
       [13.21069202],
       [16.97773556],
       [ 7.84904532],
       [ 9.01603163],
       [12.0370073 ],
       [18.97657924],
       [21.10891244],
       [17.77949782],
       [10.62693815],
       [10.36684881],
       [ 9.90298206],
       [17.32931197],
       [11.85832174],
       [ 4.47758904],
       [13.81190223],
       [ 8.81331353],
       [ 9.67530328],
       [11.44592364],
       [14.64794093],
       [10.17840799],
       [14.42184212],
       [20.78136464],
       [15.18140789],
       [11.59870739],
       [15.59378475],
       [11.71127101],
       [16.92225511],
       [ 9.99922965],
       [ 4.49631598],
       [19.15639616],
       [21.22757378],
       [10.48212385],
       [16.31492112],
       [12.63571716],
       [15.33707782],
       [24.11860723],
       [16.94035021],
       [13.87595844],
       [23.24248685],
       [17.64409385],
       [14.76221142],
       [20.30110878],
       [17.93641467],
       [ 6.12602215],
       [ 7.10850249],
       [ 3.58725841],
       [19.69293106],
       [14.7598741 ],
       [21.14027498],
       [13.88060985],
       [16.40377623],
       [15.30509593],
       [12.91968895],
       [11.97874744],
       [ 6.5707774 ],
       [15.56609348],
       [ 6.82006767],
       [14.41010605],
       [ 7.83807642],
       [13.6264571 ],
       [15.0827909 ],
       [19.45441306],
       [ 9.12734958],
       [10.57717411],
       [ 6.599669  ],
       [22.25549161],
       [ 7.88410649],
       [10.4276871 ],
       [15.57779819],
       [ 8.44915012],
       [19.26692307],
       [11.8368039 ],
       [14.00141385],
       [11.45348627],
       [20.85125198],
       [ 9.76842795],
       [19.67547632],
       [ 9.48964097],
       [18.39902932],
       [19.24986927],
       [ 8.76480262],
       [10.09133403],
       [ 9.70853872],
       [15.29422368],
       [23.26086103],
       [12.26335941],
       [ 9.8272711 ],
       [18.36720534],
       [10.0095377 ],
       [16.3600003 ],
       [18.22390132],
       [15.50161696],
       [ 5.3075589 ],
       [15.38485192],
       [10.0143112 ],
       [10.38419866],
       [12.39914823],
       [14.21383298],
       [13.55914568],
       [14.94678206],
       [17.35163608],
       [11.0682946 ],
       [14.22372138],
       [10.82439531],
       [13.36324677],
       [17.1861428 ],
       [17.9415563 ],
       [ 7.39497997],
       [14.35827373],
       [ 7.60769238],
       [11.97093887],
       [13.74435742],
       [24.78687031],
       [19.9793727 ],
       [12.1620464 ],
       [16.01099722],
       [12.38455495],
       [10.5871997 ],
       [13.92809918],
       [ 6.55467   ],
       [24.13310013],
       [18.53852096],
       [20.80301059],
       [ 9.69137313],
       [17.07644223],
       [18.64430648],
       [ 6.05162411],
       [12.4891591 ],
       [ 8.42401933],
       [ 4.46622956],
       [18.48695797],
       [16.49530044],
       [ 5.37034248],
       [ 8.16531236],
       [12.78592082],
       [23.76732149],
       [15.17319554]])

<h1> using class

In [ ]:
x_train, x_test, y_train, y_test = tts(x,y,test_size=0.2,random_state=42)

In [ ]:
y_train.shape

(160, 1)

In [ ]:
class mlr:

  def __init__(self):
    self.coeff_ = None
    self.Intercept = None

  def train(self, x_train, y_train):
    x_train = np.insert(x_train, 0, 1, axis=1)

    beta = np.linalg.inv(np.dot(x_train.T, x_train)).dot(x_train.T).dot(y_train)

    self.coeff_ = beta[1:]
    self.Intercept = beta[0]

  def predict(self,x_test):
    y_pred = np.dot(x_test,self.coeff_) + self.Intercept
    return y_pred

In [ ]:
lr = mlr()

In [ ]:
lr.train(x_train,y_train)

In [ ]:
prediction = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test,prediction)

In [ ]:
r2

0.8994380241009123

both tts and class model get the same accuracy

<h1> linear reg class

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x = df.drop('Sales',axis=1)
y = df['Sales']

x_train,x_test,y_train,y_test = tts(x,y,test_size=0.2,random_state=42)

In [ ]:
lr = LinearRegression()

lr.fit(x_train,y_train)
pre = lr.predict(x_test)

In [ ]:
r2_score(y_test,pre)

0.899438024100912